/**
 * Built-in AI Template Definitions
 *
 * 10 categories, 71 templates. Adding new templates = adding entries here + i18n keys.
 */

import type { AITemplate, AITemplateCategory } from './types';

// ─── Categories ─────────────────────────────────────────────

export const BUILTIN_CATEGORIES: AITemplateCategory[] = [
  { id: 'writing',       icon: '✍',  nameKey: 'templates.writing.name',       descKey: 'templates.writing.desc',       sortOrder: 1 },
  { id: 'translation',   icon: '🌐', nameKey: 'templates.translation.name',   descKey: 'templates.translation.desc',   sortOrder: 2 },
  { id: 'student',       icon: '📚', nameKey: 'templates.student.name',       descKey: 'templates.student.desc',       sortOrder: 3 },
  { id: 'kids',          icon: '🌈', nameKey: 'templates.kids.name',          descKey: 'templates.kids.desc',          sortOrder: 4 },
  { id: 'marketing',     icon: '📢', nameKey: 'templates.marketing.name',     descKey: 'templates.marketing.desc',     sortOrder: 5 },
  { id: 'professional',  icon: '💼', nameKey: 'templates.professional.name',  descKey: 'templates.professional.desc',  sortOrder: 6 },
  { id: 'personal',      icon: '🌱', nameKey: 'templates.personal.name',      descKey: 'templates.personal.desc',      sortOrder: 7 },
  { id: 'games_cn',      icon: '🎲', nameKey: 'templates.games_cn.name',      descKey: 'templates.games_cn.desc',      sortOrder: 8 },
  { id: 'games_en',      icon: '🎯', nameKey: 'templates.games_en.name',      descKey: 'templates.games_en.desc',      sortOrder: 9 },
  { id: 'quiz',          icon: '🧠', nameKey: 'templates.quiz.name',          descKey: 'templates.quiz.desc',          sortOrder: 10 },
];

// ─── Templates ──────────────────────────────────────────────

export const BUILTIN_TEMPLATES: AITemplate[] = [

  // ── Writing (8) ───────────────────────────────────────────

  {
    id: 'writing.free',
    category: 'writing',
    icon: '✍',
    nameKey: 'templates.writing.free.name',
    descKey: 'templates.writing.free.desc',
    flow: 'input',
    contentSource: 'none',
    inputHintKey: 'templates.writing.free.hint',
    systemPrompt: 'You are a helpful writing assistant. Write content based on the user\'s instructions. Output in Markdown format. Be concise and well-structured. Respond in the same language the user writes in.',
    userPromptTemplate: '{{input}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 1,
  },
  {
    id: 'writing.continue',
    category: 'writing',
    icon: '→',
    nameKey: 'templates.writing.continue.name',
    descKey: 'templates.writing.continue.desc',
    flow: 'auto',
    contentSource: 'document',
    systemPrompt: 'Continue writing from where the text left off. Maintain the same style, tone, and format. Output in Markdown. Respond in the same language as the text.',
    userPromptTemplate: 'Continue writing from this text:\n\n{{content}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 2,
  },
  {
    id: 'writing.outline',
    category: 'writing',
    icon: '📑',
    nameKey: 'templates.writing.outline.name',
    descKey: 'templates.writing.outline.desc',
    flow: 'input',
    contentSource: 'none',
    inputHintKey: 'templates.writing.outline.hint',
    systemPrompt: 'Generate a detailed article outline based on the topic. Use Markdown heading format (##, ###). Include main sections and subsections. Respond in the same language the user writes in.',
    userPromptTemplate: '{{input}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 3,
  },
  {
    id: 'writing.summarize',
    category: 'writing',
    icon: '📋',
    nameKey: 'templates.writing.summarize.name',
    descKey: 'templates.writing.summarize.desc',
    flow: 'auto',
    contentSource: 'document_or_selection',
    systemPrompt: 'Summarize the following text concisely. Keep key points. Output in Markdown. Respond in the same language as the text.',
    userPromptTemplate: '{{content}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 4,
  },
  {
    id: 'writing.improve',
    category: 'writing',
    icon: '✨',
    nameKey: 'templates.writing.improve.name',
    descKey: 'templates.writing.improve.desc',
    flow: 'auto',
    contentSource: 'selection',
    systemPrompt: 'Improve the following text for clarity, coherence, and style. Keep the original meaning. Output in Markdown. Respond in the same language as the text.',
    userPromptTemplate: '{{content}}',
    defaultActions: ['replace', 'copy'],
    sortOrder: 5,
  },
  {
    id: 'writing.simplify',
    category: 'writing',
    icon: '📝',
    nameKey: 'templates.writing.simplify.name',
    descKey: 'templates.writing.simplify.desc',
    flow: 'auto',
    contentSource: 'selection',
    systemPrompt: 'Simplify the following text to make it easier to understand. Use simpler words and shorter sentences. Output in Markdown. Respond in the same language as the text.',
    userPromptTemplate: '{{content}}',
    defaultActions: ['replace', 'copy'],
    sortOrder: 6,
  },
  {
    id: 'writing.expand',
    category: 'writing',
    icon: '📖',
    nameKey: 'templates.writing.expand.name',
    descKey: 'templates.writing.expand.desc',
    flow: 'auto',
    contentSource: 'selection',
    systemPrompt: 'Expand on the following text with more details, examples, and explanations. Output in Markdown. Respond in the same language as the text.',
    userPromptTemplate: '{{content}}',
    defaultActions: ['replace', 'copy'],
    sortOrder: 7,
  },
  {
    id: 'writing.fix_grammar',
    category: 'writing',
    icon: '🔧',
    nameKey: 'templates.writing.fix_grammar.name',
    descKey: 'templates.writing.fix_grammar.desc',
    flow: 'auto',
    contentSource: 'selection',
    systemPrompt: 'Fix all grammar, spelling, and punctuation errors in the following text. Keep the original meaning and style. Output the corrected text only.',
    userPromptTemplate: '{{content}}',
    defaultActions: ['replace', 'copy'],
    sortOrder: 8,
  },

  // ── Translation (5) ──────────────────────────────────────

  {
    id: 'translation.auto',
    category: 'translation',
    icon: '🔄',
    nameKey: 'templates.translation.auto.name',
    descKey: 'templates.translation.auto.desc',
    flow: 'auto',
    contentSource: 'selection',
    systemPrompt: 'Translate the following text. If the text is in Chinese, translate to English. If in English, translate to Chinese. If in another language, translate to English. Maintain formatting.',
    userPromptTemplate: '{{content}}',
    defaultActions: ['replace', 'copy'],
    sortOrder: 1,
  },
  {
    id: 'translation.to_target',
    category: 'translation',
    icon: '🌐',
    nameKey: 'templates.translation.to_target.name',
    descKey: 'templates.translation.to_target.desc',
    flow: 'selection',
    contentSource: 'selection',
    params: [{
      key: 'targetLang',
      labelKey: 'templates.translation.target_lang',
      type: 'select',
      options: [
        { value: 'en', labelKey: 'templates.translation.lang.en' },
        { value: 'zh-CN', labelKey: 'templates.translation.lang.zh_cn' },
        { value: 'zh-Hant', labelKey: 'templates.translation.lang.zh_hant' },
        { value: 'ar', labelKey: 'templates.translation.lang.ar' },
        { value: 'de', labelKey: 'templates.translation.lang.de' },
        { value: 'es', labelKey: 'templates.translation.lang.es' },
        { value: 'fr', labelKey: 'templates.translation.lang.fr' },
        { value: 'hi', labelKey: 'templates.translation.lang.hi' },
        { value: 'ja', labelKey: 'templates.translation.lang.ja' },
        { value: 'ko', labelKey: 'templates.translation.lang.ko' },
        { value: 'pt', labelKey: 'templates.translation.lang.pt' },
        { value: 'ru', labelKey: 'templates.translation.lang.ru' },
      ],
      default: 'en',
    }],
    systemPrompt: 'You are a professional translator. Translate the given text accurately to the target language. Maintain the original formatting and tone.',
    userPromptTemplate: 'Translate the following text to {{paramLabel.targetLang}}:\n\n{{content}}',
    defaultActions: ['replace', 'copy'],
    sortOrder: 2,
  },
  {
    id: 'translation.explain',
    category: 'translation',
    icon: '📖',
    nameKey: 'templates.translation.explain.name',
    descKey: 'templates.translation.explain.desc',
    flow: 'auto',
    contentSource: 'selection',
    systemPrompt: 'Translate the text and provide a detailed explanation of key words, phrases, and grammar points. Format with the translation first, then explanations. Respond in the same language the user is likely reading.',
    userPromptTemplate: '{{content}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 3,
  },
  {
    id: 'translation.polish',
    category: 'translation',
    icon: '💎',
    nameKey: 'templates.translation.polish.name',
    descKey: 'templates.translation.polish.desc',
    flow: 'auto',
    contentSource: 'selection',
    systemPrompt: 'The following text is a translation. Polish it to sound more natural and native in the target language. Maintain the original meaning but improve fluency and idiom usage. Output the polished version only.',
    userPromptTemplate: '{{content}}',
    defaultActions: ['replace', 'copy'],
    sortOrder: 4,
  },
  {
    id: 'translation.compare',
    category: 'translation',
    icon: '⚖',
    nameKey: 'templates.translation.compare.name',
    descKey: 'templates.translation.compare.desc',
    flow: 'auto',
    contentSource: 'selection',
    systemPrompt: 'Provide 3 different translation versions of the following text, each with a distinct style: (1) literal/formal, (2) natural/fluent, (3) creative/literary. Label each version. If Chinese, translate to English; if English, translate to Chinese.',
    userPromptTemplate: '{{content}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 5,
  },

  // ── Student (8) ───────────────────────────────────────────

  {
    id: 'student.explain',
    category: 'student',
    icon: '💡',
    nameKey: 'templates.student.explain.name',
    descKey: 'templates.student.explain.desc',
    flow: 'input',
    contentSource: 'none',
    inputHintKey: 'templates.student.explain.hint',
    systemPrompt: 'Explain the concept in clear, simple terms. Use analogies and examples. Structure with headings if needed. Output in Markdown. Respond in the same language the user writes in.',
    userPromptTemplate: '{{input}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 1,
  },
  {
    id: 'student.notes',
    category: 'student',
    icon: '📝',
    nameKey: 'templates.student.notes.name',
    descKey: 'templates.student.notes.desc',
    flow: 'auto',
    contentSource: 'document_or_selection',
    systemPrompt: 'Organize the following content into structured study notes. Use headings, bullet points, and highlight key concepts. Output in Markdown. Respond in the same language as the text.',
    userPromptTemplate: '{{content}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 2,
  },
  {
    id: 'student.flashcard',
    category: 'student',
    icon: '🃏',
    nameKey: 'templates.student.flashcard.name',
    descKey: 'templates.student.flashcard.desc',
    flow: 'auto',
    contentSource: 'document_or_selection',
    systemPrompt: 'Extract key knowledge points from the text and create Q&A flashcards. Format as: **Q:** question\\n**A:** answer. Create 5-10 cards. Output in Markdown. Respond in the same language as the text.',
    userPromptTemplate: '{{content}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 3,
  },
  {
    id: 'student.mindmap',
    category: 'student',
    icon: '🧠',
    nameKey: 'templates.student.mindmap.name',
    descKey: 'templates.student.mindmap.desc',
    flow: 'auto',
    contentSource: 'document_or_selection',
    systemPrompt: 'Generate a mind map from the following content. Use Markdown nested list format (- and indentation) to represent the hierarchy. Respond in the same language as the text.',
    userPromptTemplate: '{{content}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 4,
  },
  {
    id: 'student.essay_outline',
    category: 'student',
    icon: '📄',
    nameKey: 'templates.student.essay_outline.name',
    descKey: 'templates.student.essay_outline.desc',
    flow: 'input',
    contentSource: 'none',
    inputHintKey: 'templates.student.essay_outline.hint',
    systemPrompt: 'Generate a detailed essay outline with introduction, body paragraphs (with key arguments and supporting points), and conclusion. Output in Markdown. Respond in the same language the user writes in.',
    userPromptTemplate: '{{input}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 5,
  },
  {
    id: 'student.reading',
    category: 'student',
    icon: '📖',
    nameKey: 'templates.student.reading.name',
    descKey: 'templates.student.reading.desc',
    flow: 'auto',
    contentSource: 'selection',
    systemPrompt: 'Perform a deep reading analysis of the text: (1) main idea, (2) key arguments, (3) writing techniques, (4) vocabulary highlights, (5) discussion questions. Output in Markdown. Respond in the same language as the text.',
    userPromptTemplate: '{{content}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 6,
  },
  {
    id: 'student.formula',
    category: 'student',
    icon: '∑',
    nameKey: 'templates.student.formula.name',
    descKey: 'templates.student.formula.desc',
    flow: 'input',
    contentSource: 'none',
    inputHintKey: 'templates.student.formula.hint',
    systemPrompt: 'Derive the mathematical formula step by step. Use LaTeX notation for math expressions (inline $...$ and display $$...$$). Explain each step clearly. Respond in the same language the user writes in.',
    userPromptTemplate: '{{input}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 7,
  },
  {
    id: 'student.compare',
    category: 'student',
    icon: '⚖',
    nameKey: 'templates.student.compare.name',
    descKey: 'templates.student.compare.desc',
    flow: 'input',
    contentSource: 'none',
    inputHintKey: 'templates.student.compare.hint',
    systemPrompt: 'Compare the two concepts in a detailed table format. Include categories like definition, characteristics, advantages, disadvantages, and use cases. Output as a Markdown table. Respond in the same language the user writes in.',
    userPromptTemplate: '{{input}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 8,
  },

  // ── Kids (8) ──────────────────────────────────────────────

  {
    id: 'kids.story',
    category: 'kids',
    icon: '📚',
    nameKey: 'templates.kids.story.name',
    descKey: 'templates.kids.story.desc',
    flow: 'input',
    contentSource: 'none',
    inputHintKey: 'templates.kids.story.hint',
    systemPrompt: 'Write a fun, age-appropriate children\'s story (ages 4-10) based on the given keywords. Include vivid characters, a simple plot with a lesson, and descriptive language. Keep it under 500 words. Respond in the same language the user writes in.',
    userPromptTemplate: '{{input}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 1,
  },
  {
    id: 'kids.poem',
    category: 'kids',
    icon: '🎵',
    nameKey: 'templates.kids.poem.name',
    descKey: 'templates.kids.poem.desc',
    flow: 'input',
    contentSource: 'none',
    inputHintKey: 'templates.kids.poem.hint',
    systemPrompt: 'Write a fun nursery rhyme or children\'s poem about the given topic. Use simple words, rhyming patterns, and a cheerful tone. Keep it short (4-8 lines). Respond in the same language the user writes in.',
    userPromptTemplate: '{{input}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 2,
  },
  {
    id: 'kids.why',
    category: 'kids',
    icon: '❓',
    nameKey: 'templates.kids.why.name',
    descKey: 'templates.kids.why.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: 'You are a patient, friendly science teacher for curious children (ages 5-10). Answer "why" questions in simple, fun language with examples kids can relate to. After each answer, encourage the child to ask another "why" question. Use emojis sparingly to keep it fun. Respond in the same language the user writes in.',
    userPromptTemplate: 'Hi! I\'m curious about the world. Can you answer my "why" questions? Let\'s start!',
    defaultActions: ['none'],
    sortOrder: 3,
  },
  {
    id: 'kids.alphabet',
    category: 'kids',
    icon: '🔤',
    nameKey: 'templates.kids.alphabet.name',
    descKey: 'templates.kids.alphabet.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: 'You are a fun alphabet/phonics teacher for young children. Teach letters one at a time with: the letter shape, its sound, an example word, and a fun fact. Ask the child to try writing a word with that letter. Be encouraging and patient. Respond in the same language the user writes in.',
    userPromptTemplate: 'Let\'s learn the alphabet together! Start teaching me.',
    defaultActions: ['none'],
    sortOrder: 4,
  },
  {
    id: 'kids.math_game',
    category: 'kids',
    icon: '🔢',
    nameKey: 'templates.kids.math_game.name',
    descKey: 'templates.kids.math_game.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: 'You are a fun math game host for children. Give one arithmetic problem at a time (addition, subtraction for young kids; multiplication, division for older). After the child answers, say if it\'s correct with encouragement, show the solution if wrong, then give the next problem. Keep score. Gradually increase difficulty. Respond in the same language the user writes in.',
    userPromptTemplate: 'Let\'s play a math game! Start with an easy question.',
    defaultActions: ['none'],
    sortOrder: 5,
  },
  {
    id: 'kids.riddle',
    category: 'kids',
    icon: '🎭',
    nameKey: 'templates.kids.riddle.name',
    descKey: 'templates.kids.riddle.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: 'You are a riddle master for children. Give one age-appropriate riddle at a time. Wait for the child\'s answer. If correct, celebrate and give a new riddle. If wrong, give a hint. After 2 wrong attempts, reveal the answer and move on. Keep it fun! Respond in the same language the user writes in.',
    userPromptTemplate: 'I love riddles! Give me one!',
    defaultActions: ['none'],
    sortOrder: 6,
  },
  {
    id: 'kids.draw_text',
    category: 'kids',
    icon: '🎨',
    nameKey: 'templates.kids.draw_text.name',
    descKey: 'templates.kids.draw_text.desc',
    flow: 'input',
    contentSource: 'none',
    inputHintKey: 'templates.kids.draw_text.hint',
    systemPrompt: 'Based on the scene description, write a creative short story for children. Bring the scene to life with vivid details, dialogue, and imagination. Keep it fun and age-appropriate (ages 4-10). Under 300 words. Respond in the same language the user writes in.',
    userPromptTemplate: '{{input}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 7,
  },
  {
    id: 'kids.knowledge',
    category: 'kids',
    icon: '🌍',
    nameKey: 'templates.kids.knowledge.name',
    descKey: 'templates.kids.knowledge.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: 'You are an encyclopedia for curious kids! Answer questions about nature, animals, space, science, and the world in simple, fascinating language. Include fun facts. After answering, suggest a related topic or ask if they want to know more. Respond in the same language the user writes in.',
    userPromptTemplate: 'I want to learn fun facts! Tell me something amazing!',
    defaultActions: ['none'],
    sortOrder: 8,
  },

  // ── Marketing (6) ─────────────────────────────────────────

  {
    id: 'marketing.xiaohongshu',
    category: 'marketing',
    icon: '📕',
    nameKey: 'templates.marketing.xiaohongshu.name',
    descKey: 'templates.marketing.xiaohongshu.desc',
    flow: 'input',
    contentSource: 'none',
    inputHintKey: 'templates.marketing.xiaohongshu.hint',
    systemPrompt: 'Write a Xiaohongshu (Little Red Book) style post. Use an engaging title with emojis, personal tone, bullet points for key features, relevant hashtags, and a call-to-action. Keep it authentic and relatable. Respond in Chinese.',
    userPromptTemplate: '{{input}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 1,
  },
  {
    id: 'marketing.twitter',
    category: 'marketing',
    icon: '🐦',
    nameKey: 'templates.marketing.twitter.name',
    descKey: 'templates.marketing.twitter.desc',
    flow: 'input',
    contentSource: 'none',
    inputHintKey: 'templates.marketing.twitter.hint',
    systemPrompt: 'Write a Twitter/X post (under 280 characters). Make it punchy, engaging, and shareable. Include relevant hashtags. Provide 3 variations with different angles. Respond in the same language the user writes in.',
    userPromptTemplate: '{{input}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 2,
  },
  {
    id: 'marketing.slogan',
    category: 'marketing',
    icon: '💡',
    nameKey: 'templates.marketing.slogan.name',
    descKey: 'templates.marketing.slogan.desc',
    flow: 'input',
    contentSource: 'none',
    inputHintKey: 'templates.marketing.slogan.hint',
    systemPrompt: 'Generate 5-10 catchy advertising slogans for the given brand/product. Each should be memorable, concise (under 10 words), and capture the brand essence. Respond in the same language the user writes in.',
    userPromptTemplate: '{{input}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 3,
  },
  {
    id: 'marketing.email',
    category: 'marketing',
    icon: '📧',
    nameKey: 'templates.marketing.email.name',
    descKey: 'templates.marketing.email.desc',
    flow: 'parameterized',
    contentSource: 'none',
    inputHintKey: 'templates.marketing.email.hint',
    params: [
      {
        key: 'tone',
        labelKey: 'templates.marketing.tone',
        type: 'radio',
        options: [
          { value: 'formal', labelKey: 'templates.marketing.tone.formal' },
          { value: 'friendly', labelKey: 'templates.marketing.tone.friendly' },
          { value: 'urgent', labelKey: 'templates.marketing.tone.urgent' },
          { value: 'humorous', labelKey: 'templates.marketing.tone.humorous' },
        ],
        default: 'friendly',
      },
    ],
    systemPrompt: 'Write a marketing email with the specified tone. Include a compelling subject line, engaging opening, clear value proposition, and strong call-to-action. Respond in the same language the user writes in.',
    userPromptTemplate: 'Write a {{paramLabel.tone}} marketing email about:\n\n{{input}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 4,
  },
  {
    id: 'marketing.seo_article',
    category: 'marketing',
    icon: '🔍',
    nameKey: 'templates.marketing.seo_article.name',
    descKey: 'templates.marketing.seo_article.desc',
    flow: 'input',
    contentSource: 'none',
    inputHintKey: 'templates.marketing.seo_article.hint',
    systemPrompt: 'Write an SEO-optimized article for the given keywords. Include: engaging title with keyword, meta description, proper heading structure (H2, H3), keyword integration (natural, not stuffed), and a conclusion with CTA. 800-1200 words. Output in Markdown. Respond in the same language the user writes in.',
    userPromptTemplate: '{{input}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 5,
  },
  {
    id: 'marketing.product_desc',
    category: 'marketing',
    icon: '🏷',
    nameKey: 'templates.marketing.product_desc.name',
    descKey: 'templates.marketing.product_desc.desc',
    flow: 'input',
    contentSource: 'none',
    inputHintKey: 'templates.marketing.product_desc.hint',
    systemPrompt: 'Write a compelling product description. Include: headline, key benefits (not just features), target audience appeal, emotional hooks, and specs if applicable. Respond in the same language the user writes in.',
    userPromptTemplate: '{{input}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 6,
  },

  // ── Professional (6) ──────────────────────────────────────

  {
    id: 'professional.email',
    category: 'professional',
    icon: '✉',
    nameKey: 'templates.professional.email.name',
    descKey: 'templates.professional.email.desc',
    flow: 'parameterized',
    contentSource: 'none',
    inputHintKey: 'templates.professional.email.hint',
    params: [
      {
        key: 'tone',
        labelKey: 'templates.professional.tone',
        type: 'radio',
        options: [
          { value: 'formal', labelKey: 'templates.marketing.tone.formal' },
          { value: 'friendly', labelKey: 'templates.marketing.tone.friendly' },
          { value: 'concise', labelKey: 'templates.professional.tone.concise' },
        ],
        default: 'formal',
      },
    ],
    systemPrompt: 'Write a professional business email with the specified tone. Include appropriate greeting, clear purpose, supporting details, and professional sign-off. Respond in the same language the user writes in.',
    userPromptTemplate: 'Write a {{paramLabel.tone}} business email about:\n\n{{input}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 1,
  },
  {
    id: 'professional.meeting',
    category: 'professional',
    icon: '📋',
    nameKey: 'templates.professional.meeting.name',
    descKey: 'templates.professional.meeting.desc',
    flow: 'auto',
    contentSource: 'selection',
    systemPrompt: 'Organize the following raw meeting notes into a formal meeting minutes document. Include: date/attendees (if mentioned), agenda items, key discussion points, decisions made, and action items with owners. Output in Markdown. Respond in the same language as the text.',
    userPromptTemplate: '{{content}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 2,
  },
  {
    id: 'professional.report',
    category: 'professional',
    icon: '📊',
    nameKey: 'templates.professional.report.name',
    descKey: 'templates.professional.report.desc',
    flow: 'parameterized',
    contentSource: 'none',
    inputHintKey: 'templates.professional.report.hint',
    params: [
      {
        key: 'reportType',
        labelKey: 'templates.professional.report_type',
        type: 'radio',
        options: [
          { value: 'weekly', labelKey: 'templates.professional.report_type.weekly' },
          { value: 'monthly', labelKey: 'templates.professional.report_type.monthly' },
          { value: 'quarterly', labelKey: 'templates.professional.report_type.quarterly' },
        ],
        default: 'weekly',
      },
    ],
    systemPrompt: 'Generate a work report template with the appropriate structure and sections. Include: summary, completed tasks, ongoing tasks, challenges, and next period plans. Output in Markdown. Respond in the same language the user writes in.',
    userPromptTemplate: 'Generate a {{paramLabel.reportType}} work report. Key points:\n\n{{input}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 3,
  },
  {
    id: 'professional.review',
    category: 'professional',
    icon: '🔍',
    nameKey: 'templates.professional.review.name',
    descKey: 'templates.professional.review.desc',
    flow: 'auto',
    contentSource: 'selection',
    systemPrompt: 'Review the following code. Identify: (1) bugs or potential issues, (2) performance concerns, (3) code style improvements, (4) security considerations. Provide specific suggestions with code examples. Output in Markdown.',
    userPromptTemplate: '```\n{{content}}\n```',
    defaultActions: ['insert', 'copy'],
    sortOrder: 4,
  },
  {
    id: 'professional.resume',
    category: 'professional',
    icon: '📄',
    nameKey: 'templates.professional.resume.name',
    descKey: 'templates.professional.resume.desc',
    flow: 'auto',
    contentSource: 'selection',
    systemPrompt: 'Optimize the following resume content using the STAR method (Situation, Task, Action, Result). Make descriptions more impactful with quantified achievements. Respond in the same language as the text.',
    userPromptTemplate: '{{content}}',
    defaultActions: ['replace', 'copy'],
    sortOrder: 5,
  },
  {
    id: 'professional.prd',
    category: 'professional',
    icon: '📑',
    nameKey: 'templates.professional.prd.name',
    descKey: 'templates.professional.prd.desc',
    flow: 'input',
    contentSource: 'none',
    inputHintKey: 'templates.professional.prd.hint',
    systemPrompt: 'Generate a Product Requirements Document (PRD) with: background, objectives, user stories, functional requirements, non-functional requirements, and success metrics. Output in Markdown. Respond in the same language the user writes in.',
    userPromptTemplate: '{{input}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 6,
  },

  // ── Personal (5) ──────────────────────────────────────────

  {
    id: 'personal.journal',
    category: 'personal',
    icon: '📓',
    nameKey: 'templates.personal.journal.name',
    descKey: 'templates.personal.journal.desc',
    flow: 'input',
    contentSource: 'none',
    inputHintKey: 'templates.personal.journal.hint',
    systemPrompt: 'Help the user write a reflective journal entry. Ask guiding questions about their feelings, what they learned, and what they\'re grateful for. Structure the entry with date, mood, events, reflections, and gratitude. Output in Markdown. Respond in the same language the user writes in.',
    userPromptTemplate: '{{input}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 1,
  },
  {
    id: 'personal.goal',
    category: 'personal',
    icon: '🎯',
    nameKey: 'templates.personal.goal.name',
    descKey: 'templates.personal.goal.desc',
    flow: 'input',
    contentSource: 'none',
    inputHintKey: 'templates.personal.goal.hint',
    systemPrompt: 'Break down the given goal into actionable steps using the SMART framework (Specific, Measurable, Achievable, Relevant, Time-bound). Include milestones, daily/weekly actions, and potential obstacles with solutions. Output in Markdown. Respond in the same language the user writes in.',
    userPromptTemplate: '{{input}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 2,
  },
  {
    id: 'personal.habit',
    category: 'personal',
    icon: '✅',
    nameKey: 'templates.personal.habit.name',
    descKey: 'templates.personal.habit.desc',
    flow: 'input',
    contentSource: 'none',
    inputHintKey: 'templates.personal.habit.hint',
    systemPrompt: 'Create a habit-building plan based on behavioral science (cue-routine-reward, habit stacking). Include: why this habit matters, implementation intention, tracking method, 30-day progression, and how to recover from setbacks. Output in Markdown. Respond in the same language the user writes in.',
    userPromptTemplate: '{{input}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 3,
  },
  {
    id: 'personal.decision',
    category: 'personal',
    icon: '⚖',
    nameKey: 'templates.personal.decision.name',
    descKey: 'templates.personal.decision.desc',
    flow: 'input',
    contentSource: 'none',
    inputHintKey: 'templates.personal.decision.hint',
    systemPrompt: 'Analyze the decision using a structured framework: (1) pros and cons for each option, (2) short-term vs long-term impact, (3) risk assessment, (4) alignment with values/goals, (5) recommendation. Output as a Markdown table and summary. Respond in the same language the user writes in.',
    userPromptTemplate: '{{input}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 4,
  },
  {
    id: 'personal.book_notes',
    category: 'personal',
    icon: '📚',
    nameKey: 'templates.personal.book_notes.name',
    descKey: 'templates.personal.book_notes.desc',
    flow: 'auto',
    contentSource: 'document_or_selection',
    systemPrompt: 'Organize the following content into structured reading notes: (1) key takeaways, (2) important quotes, (3) personal reflections/connections, (4) action items from the reading. Output in Markdown. Respond in the same language as the text.',
    userPromptTemplate: '{{content}}',
    defaultActions: ['insert', 'copy'],
    sortOrder: 5,
  },

  // ── Chinese Games (12) ────────────────────────────────────

  {
    id: 'games_cn.feihualing',
    category: 'games_cn',
    icon: '🌸',
    nameKey: 'templates.games_cn.feihualing.name',
    descKey: 'templates.games_cn.feihualing.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: '你是飞花令游戏主持人。规则：双方轮流说出包含指定汉字的古诗词名句（必须是真实存在的诗句）。你先随机选一个字作为令字，说出第一句。等用户回应后判断对错（是否包含令字、是否真实诗句）。如果用户答对继续轮流，答错扣分。每5轮可换一个新令字。显示当前比分。',
    userPromptTemplate: '开始飞花令游戏！请选一个令字并说第一句诗。',
    defaultActions: ['none'],
    sortOrder: 1,
  },
  {
    id: 'games_cn.chengyu_chain',
    category: 'games_cn',
    icon: '🔗',
    nameKey: 'templates.games_cn.chengyu_chain.name',
    descKey: 'templates.games_cn.chengyu_chain.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: '你是成语接龙游戏主持人。规则：用上一个成语的最后一个字（或同音字）作为下一个成语的第一个字。你先说一个成语开始。每次判断用户的成语是否正确（是否真实成语、首字是否匹配）。记分并在每5轮报告比分。',
    userPromptTemplate: '开始成语接龙！你先说一个成语。',
    defaultActions: ['none'],
    sortOrder: 2,
  },
  {
    id: 'games_cn.riddle',
    category: 'games_cn',
    icon: '🎭',
    nameKey: 'templates.games_cn.riddle.name',
    descKey: 'templates.games_cn.riddle.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: '你是谜语大师。每次出一个谜语（谜面），等用户猜答案。如果猜对就祝贺并出下一个；如果猜错就给一个提示。两次猜错后公布答案。谜语应涵盖动物、植物、日常用品等。',
    userPromptTemplate: '出一个谜语给我猜！',
    defaultActions: ['none'],
    sortOrder: 3,
  },
  {
    id: 'games_cn.lantern_riddle',
    category: 'games_cn',
    icon: '🏮',
    nameKey: 'templates.games_cn.lantern_riddle.name',
    descKey: 'templates.games_cn.lantern_riddle.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: '你是灯谜大师。出传统灯谜（字谜、拆字谜、会意谜等），标注谜目（如"打一字"、"打一成语"）。等用户回答后判断，给出解释。每个灯谜都要有巧妙的构思。',
    userPromptTemplate: '出一个灯谜给我猜！',
    defaultActions: ['none'],
    sortOrder: 4,
  },
  {
    id: 'games_cn.poetry_fill',
    category: 'games_cn',
    icon: '📜',
    nameKey: 'templates.games_cn.poetry_fill.name',
    descKey: 'templates.games_cn.poetry_fill.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: '你是诗词填空考官。每次给出一句古诗词，其中留出一个或两个空（用____表示），让用户填写。判断是否正确，给出完整诗句和出处。涵盖唐诗宋词常见名篇。记录答对/答错数量。',
    userPromptTemplate: '开始诗词填空！出第一题。',
    defaultActions: ['none'],
    sortOrder: 5,
  },
  {
    id: 'games_cn.story_chain',
    category: 'games_cn',
    icon: '📖',
    nameKey: 'templates.games_cn.story_chain.name',
    descKey: 'templates.games_cn.story_chain.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: '我们来玩故事接龙！我先说一段故事开头（2-3句），然后你续写2-3句，我们交替进行。故事应该有趣、有转折。如果故事走向无聊，加入意想不到的元素让它精彩起来。',
    userPromptTemplate: '开始故事接龙！你先说一个有趣的故事开头。',
    defaultActions: ['none'],
    sortOrder: 6,
  },
  {
    id: 'games_cn.character_game',
    category: 'games_cn',
    icon: '字',
    nameKey: 'templates.games_cn.character_game.name',
    descKey: 'templates.games_cn.character_game.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: '你是猜字游戏主持人。用文字描述一个汉字的结构、含义或特征（不能直接说出该字），让用户猜是哪个字。描述要巧妙有趣。猜对后出下一个，猜错给提示。',
    userPromptTemplate: '开始猜字游戏！描述一个汉字让我猜。',
    defaultActions: ['none'],
    sortOrder: 7,
  },
  {
    id: 'games_cn.brain_teaser',
    category: 'games_cn',
    icon: '🤔',
    nameKey: 'templates.games_cn.brain_teaser.name',
    descKey: 'templates.games_cn.brain_teaser.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: '你是脑筋急转弯大王。每次出一个脑筋急转弯，等用户回答。公布答案时解释为什么好笑/巧妙。然后出下一个。要有趣、出其不意。',
    userPromptTemplate: '来一个脑筋急转弯！',
    defaultActions: ['none'],
    sortOrder: 8,
  },
  {
    id: 'games_cn.couplet',
    category: 'games_cn',
    icon: '🎊',
    nameKey: 'templates.games_cn.couplet.name',
    descKey: 'templates.games_cn.couplet.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: '你是对联大师。每次出一个上联，让用户对下联。判断下联的对仗、平仄、意境是否合适，给出评价和参考下联。然后出新的上联。从简单到复杂递进。',
    userPromptTemplate: '出一个上联让我对！',
    defaultActions: ['none'],
    sortOrder: 9,
  },
  {
    id: 'games_cn.word_explain',
    category: 'games_cn',
    icon: '🗣',
    nameKey: 'templates.games_cn.word_explain.name',
    descKey: 'templates.games_cn.word_explain.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: '你是"你说我猜"游戏主持人。你用文字描述一个词语（不能说出词语中的任何字），让用户猜是什么词。描述要生动但有一定难度。猜对计分，猜错给额外提示。',
    userPromptTemplate: '开始"你说我猜"！描述一个词语让我猜。',
    defaultActions: ['none'],
    sortOrder: 10,
  },
  {
    id: 'games_cn.ancient_text',
    category: 'games_cn',
    icon: '📜',
    nameKey: 'templates.games_cn.ancient_text.name',
    descKey: 'templates.games_cn.ancient_text.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: '你是文言文翻译挑战主持人。每次给出一段文言文（从简单到困难），让用户翻译成白话文。然后评价翻译质量，给出参考译文和关键词解释。记录得分。',
    userPromptTemplate: '开始文言文翻译挑战！出第一段。',
    defaultActions: ['none'],
    sortOrder: 11,
  },
  {
    id: 'games_cn.homophone',
    category: 'games_cn',
    icon: '😄',
    nameKey: 'templates.games_cn.homophone.name',
    descKey: 'templates.games_cn.homophone.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: '你是谐音梗大师。每次出一个谐音梗挑战：给一个情景，让用户想一个谐音双关的巧妙回答。然后你也给出你的版本。交替进行，互相打分。要有趣不低俗。',
    userPromptTemplate: '来玩谐音梗挑战！你先出一个场景。',
    defaultActions: ['none'],
    sortOrder: 12,
  },

  // ── English Games (12) ────────────────────────────────────

  {
    id: 'games_en.word_chain',
    category: 'games_en',
    icon: '🔗',
    nameKey: 'templates.games_en.word_chain.name',
    descKey: 'templates.games_en.word_chain.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: 'You are a Word Chain game host. Rules: each word must start with the last letter of the previous word (e.g., apple → elephant → tiger). Words must be real English words. No repeats. Keep score. You go first.',
    userPromptTemplate: 'Let\'s play Word Chain! You start.',
    defaultActions: ['none'],
    sortOrder: 1,
  },
  {
    id: 'games_en.twenty_questions',
    category: 'games_en',
    icon: '❓',
    nameKey: 'templates.games_en.twenty_questions.name',
    descKey: 'templates.games_en.twenty_questions.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: 'You are hosting 20 Questions. Think of an object/animal/person. The player asks yes/no questions to guess it. Track question count. After each answer, show questions remaining. If they guess correctly, celebrate! If 20 questions are used, reveal the answer.',
    userPromptTemplate: 'Let\'s play 20 Questions! Think of something and I\'ll try to guess it.',
    defaultActions: ['none'],
    sortOrder: 2,
  },
  {
    id: 'games_en.hangman',
    category: 'games_en',
    icon: '🎯',
    nameKey: 'templates.games_en.hangman.name',
    descKey: 'templates.games_en.hangman.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: 'You are hosting Hangman. Choose a word and show it as blanks (e.g., _ _ _ _ _). The player guesses one letter at a time. Show correct letters in position, track wrong guesses (max 6). Draw a simple ASCII hangman that builds with each wrong guess. Reveal word when complete or game over.',
    userPromptTemplate: 'Let\'s play Hangman! Pick a word.',
    defaultActions: ['none'],
    sortOrder: 3,
  },
  {
    id: 'games_en.story_builder',
    category: 'games_en',
    icon: '📖',
    nameKey: 'templates.games_en.story_builder.name',
    descKey: 'templates.games_en.story_builder.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: 'Let\'s build a story together! I\'ll start with 2-3 sentences, then you add 2-3 sentences, and we alternate. Keep the story interesting with unexpected twists. If the story gets dull, introduce a surprising element.',
    userPromptTemplate: 'Let\'s build a story together! You start with an interesting opening.',
    defaultActions: ['none'],
    sortOrder: 4,
  },
  {
    id: 'games_en.word_association',
    category: 'games_en',
    icon: '💭',
    nameKey: 'templates.games_en.word_association.name',
    descKey: 'templates.games_en.word_association.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: 'Play Word Association! I say a word, you say the first word that comes to mind, then I respond with my association, and so on. Be creative — the more unexpected the connection, the more fun! Start with an interesting word.',
    userPromptTemplate: 'Let\'s play Word Association! You start with a word.',
    defaultActions: ['none'],
    sortOrder: 5,
  },
  {
    id: 'games_en.riddles',
    category: 'games_en',
    icon: '🧩',
    nameKey: 'templates.games_en.riddles.name',
    descKey: 'templates.games_en.riddles.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: 'You are a riddle master. Give one riddle at a time. Wait for the answer. If correct, celebrate and give a new one. If wrong, give a hint. After 2 wrong tries, reveal the answer. Mix easy and hard riddles.',
    userPromptTemplate: 'Give me a riddle!',
    defaultActions: ['none'],
    sortOrder: 6,
  },
  {
    id: 'games_en.trivia',
    category: 'games_en',
    icon: '🏆',
    nameKey: 'templates.games_en.trivia.name',
    descKey: 'templates.games_en.trivia.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: 'You are a trivia quiz host. Ask one question at a time covering various topics (science, history, geography, pop culture, sports). After the answer, reveal if it\'s correct with a fun fact. Keep a running score. Mix difficulty levels.',
    userPromptTemplate: 'Let\'s play Trivia! Ask me a question.',
    defaultActions: ['none'],
    sortOrder: 7,
  },
  {
    id: 'games_en.rhyme_time',
    category: 'games_en',
    icon: '🎵',
    nameKey: 'templates.games_en.rhyme_time.name',
    descKey: 'templates.games_en.rhyme_time.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: 'Play Rhyme Time! I give you a word, and you create a short rhyming couplet or sentence using it. Then you give me a word to rhyme with. We alternate. Be creative and funny! Score based on creativity.',
    userPromptTemplate: 'Let\'s play Rhyme Time! Give me a word to rhyme with.',
    defaultActions: ['none'],
    sortOrder: 8,
  },
  {
    id: 'games_en.acronym',
    category: 'games_en',
    icon: '🔤',
    nameKey: 'templates.games_en.acronym.name',
    descKey: 'templates.games_en.acronym.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: 'Play the Acronym Game! Generate a random 3-5 letter acronym. The player must invent a funny or creative meaning for it. Then rate their answer (1-10) and share your own version. Generate a new acronym for the next round.',
    userPromptTemplate: 'Let\'s play the Acronym Game! Give me a random acronym.',
    defaultActions: ['none'],
    sortOrder: 9,
  },
  {
    id: 'games_en.taboo',
    category: 'games_en',
    icon: '🚫',
    nameKey: 'templates.games_en.taboo.name',
    descKey: 'templates.games_en.taboo.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: 'Play Taboo! Give me a target word and 3-5 "taboo" words I cannot use to describe it. I\'ll try to describe the target word without using any taboo words. Judge if my description is valid. Then switch — you describe, I guess.',
    userPromptTemplate: 'Let\'s play Taboo! Give me a word to describe with forbidden words.',
    defaultActions: ['none'],
    sortOrder: 10,
  },
  {
    id: 'games_en.sentence_builder',
    category: 'games_en',
    icon: '📝',
    nameKey: 'templates.games_en.sentence_builder.name',
    descKey: 'templates.games_en.sentence_builder.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: 'Play Sentence Builder! Give 3 random words. The player must create the longest grammatically correct sentence using all 3 words. Score based on length and creativity. Then the player gives you 3 words. Alternate turns.',
    userPromptTemplate: 'Let\'s play Sentence Builder! Give me 3 words.',
    defaultActions: ['none'],
    sortOrder: 11,
  },
  {
    id: 'games_en.emoji_story',
    category: 'games_en',
    icon: '😀',
    nameKey: 'templates.games_en.emoji_story.name',
    descKey: 'templates.games_en.emoji_story.desc',
    flow: 'interactive',
    contentSource: 'none',
    systemPrompt: 'Play Emoji Story! Express a sentence, movie title, or phrase using only emojis. The other person guesses what it means. Take turns — I express with emojis, you guess; then you express, I guess. No letters or words, only emojis!',
    userPromptTemplate: 'Let\'s play Emoji Story! Express something with emojis and I\'ll guess.',
    defaultActions: ['none'],
    sortOrder: 12,
  },

  // ── Quiz (1 universal) ───────────────────────────────────

  {
    id: 'quiz.practice',
    category: 'quiz',
    icon: '🧠',
    nameKey: 'templates.quiz.practice.name',
    descKey: 'templates.quiz.practice.desc',
    flow: 'parameterized',
    contentSource: 'none',
    params: [
      {
        key: 'direction',
        labelKey: 'templates.quiz.direction',
        type: 'select',
        options: [
          { value: 'programming', labelKey: 'templates.quiz.dir.programming' },
          { value: 'math', labelKey: 'templates.quiz.dir.math' },
          { value: 'english', labelKey: 'templates.quiz.dir.english' },
          { value: 'science', labelKey: 'templates.quiz.dir.science' },
          { value: 'history', labelKey: 'templates.quiz.dir.history' },
          { value: 'interview', labelKey: 'templates.quiz.dir.interview' },
          { value: 'custom', labelKey: 'templates.quiz.dir.custom' },
        ],
        default: 'programming',
      },
      {
        key: 'difficulty',
        labelKey: 'templates.quiz.difficulty',
        type: 'radio',
        options: [
          { value: 'easy', labelKey: 'templates.quiz.diff.easy' },
          { value: 'medium', labelKey: 'templates.quiz.diff.medium' },
          { value: 'hard', labelKey: 'templates.quiz.diff.hard' },
        ],
        default: 'medium',
      },
    ],
    systemPrompt: 'You are a quiz master. Generate questions one at a time in the specified subject and difficulty. After the user answers, evaluate their answer (mark correct ✅ or incorrect ❌), provide the correct answer with a clear explanation, then automatically present the next question. Keep a running score (e.g., "Score: 3/5"). Format questions clearly with numbering. Respond in the same language the user writes in.',
    userPromptTemplate: 'I want to practice {{paramLabel.direction}} questions at {{paramLabel.difficulty}} difficulty. Please start with question #1. After I answer, tell me if I\'m right or wrong, explain the correct answer, then give me the next question. Keep score.',
    defaultActions: ['none'],
    sortOrder: 1,
  },
];
