/**
 * Built-in color themes for Moraya.
 * Each theme defines CSS custom property overrides.
 */

export interface ColorTheme {
  id: string;
  name: string;
  type: 'light' | 'dark';
  colors: Record<string, string>;
}

export const builtinThemes: ColorTheme[] = [
  // ── Light themes ──
  {
    id: 'default-light',
    name: 'Default Light',
    type: 'light',
    colors: {
      '--bg-primary': '#ffffff',
      '--bg-secondary': '#f8f9fa',
      '--bg-sidebar': '#f0f1f3',
      '--bg-titlebar': '#fafafa',
      '--bg-hover': '#e9ecef',
      '--bg-active': '#dee2e6',
      '--text-primary': '#1a1a1a',
      '--text-secondary': '#6c757d',
      '--text-muted': '#adb5bd',
      '--border-color': '#e0e0e0',
      '--border-light': '#f0f0f0',
      '--accent-color': '#4a90d9',
      '--accent-hover': '#357abd',
      '--scrollbar-thumb': '#c1c1c1',
    },
  },
  {
    id: 'github',
    name: 'Github',
    type: 'light',
    colors: {
      '--bg-primary': '#ffffff',
      '--bg-secondary': '#f6f8fa',
      '--bg-sidebar': '#f0f1f3',
      '--bg-titlebar': '#f6f8fa',
      '--bg-hover': '#eaeef2',
      '--bg-active': '#d0d7de',
      '--text-primary': '#1f2328',
      '--text-secondary': '#656d76',
      '--text-muted': '#8b949e',
      '--border-color': '#d0d7de',
      '--border-light': '#d8dee4',
      '--accent-color': '#0969da',
      '--accent-hover': '#0550ae',
      '--scrollbar-thumb': '#c1c1c1',
      '--hljs-keyword': '#cf222e',
      '--hljs-string': '#0a3069',
      '--hljs-number': '#0550ae',
      '--hljs-comment': '#6e7781',
      '--hljs-function': '#8250df',
      '--hljs-variable': '#953800',
      '--hljs-type': '#0550ae',
      '--hljs-built-in': '#953800',
      '--hljs-literal': '#0550ae',
      '--hljs-title': '#8250df',
      '--hljs-params': '#24292f',
      '--hljs-meta': '#6e7781',
      '--hljs-tag': '#116329',
      '--hljs-name': '#116329',
      '--hljs-attr': '#0550ae',
      '--hljs-attribute': '#0a3069',
      '--hljs-selector': '#116329',
      '--hljs-property': '#0550ae',
      '--hljs-punctuation': '#24292f',
      '--hljs-operator': '#cf222e',
      '--hljs-regexp': '#0a3069',
      '--hljs-subst': '#953800',
      '--hljs-variable-constant': '#0550ae',
      '--hljs-title-class-inherited': '#116329',
      '--hljs-selector-attr': '#8250df',
      '--hljs-section': '#0550ae',
      '--hljs-bullet': '#953800',
      '--hljs-link': '#0969da',
      '--hljs-quote': '#6e7781',
      '--hljs-code': '#953800',
      '--hljs-addition-color': '#116329',
      '--hljs-addition-bg': 'rgba(17, 99, 41, 0.1)',
      '--hljs-deletion-color': '#82071e',
      '--hljs-deletion-bg': 'rgba(130, 7, 30, 0.1)',
    },
  },
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    type: 'light',
    colors: {
      '--bg-primary': '#fdf6e3',
      '--bg-secondary': '#eee8d5',
      '--bg-sidebar': '#eee8d5',
      '--bg-titlebar': '#fdf6e3',
      '--bg-hover': '#e8e1cc',
      '--bg-active': '#ddd6c1',
      '--text-primary': '#586e75',
      '--text-secondary': '#839496',
      '--text-muted': '#93a1a1',
      '--border-color': '#d6ccb3',
      '--border-light': '#eee8d5',
      '--accent-color': '#268bd2',
      '--accent-hover': '#1a6da0',
      '--scrollbar-thumb': '#c1b899',
      '--hljs-keyword': '#859900',
      '--hljs-string': '#2aa198',
      '--hljs-number': '#d33682',
      '--hljs-comment': '#93a1a1',
      '--hljs-function': '#268bd2',
      '--hljs-variable': '#b58900',
      '--hljs-type': '#b58900',
      '--hljs-built-in': '#cb4b16',
      '--hljs-literal': '#2aa198',
      '--hljs-title': '#268bd2',
      '--hljs-params': '#657b83',
      '--hljs-meta': '#dc322f',
      '--hljs-tag': '#268bd2',
      '--hljs-name': '#268bd2',
      '--hljs-attr': '#b58900',
      '--hljs-attribute': '#2aa198',
      '--hljs-selector': '#859900',
      '--hljs-property': '#268bd2',
      '--hljs-punctuation': '#586e75',
      '--hljs-operator': '#859900',
      '--hljs-regexp': '#dc322f',
      '--hljs-subst': '#b58900',
      '--hljs-variable-constant': '#cb4b16',
      '--hljs-title-class-inherited': '#859900',
      '--hljs-selector-attr': '#b58900',
      '--hljs-section': '#cb4b16',
      '--hljs-bullet': '#cb4b16',
      '--hljs-link': '#268bd2',
      '--hljs-quote': '#93a1a1',
      '--hljs-code': '#dc322f',
      '--hljs-addition-color': '#859900',
      '--hljs-addition-bg': 'rgba(133, 153, 0, 0.1)',
      '--hljs-deletion-color': '#dc322f',
      '--hljs-deletion-bg': 'rgba(220, 50, 47, 0.1)',
    },
  },

  // ── Dark themes ──
  {
    id: 'default-dark',
    name: 'Default Dark',
    type: 'dark',
    colors: {
      '--bg-primary': '#1e1e1e',
      '--bg-secondary': '#252526',
      '--bg-sidebar': '#1c1c1e',
      '--bg-titlebar': '#2d2d2d',
      '--bg-hover': '#2a2d2e',
      '--bg-active': '#37373d',
      '--text-primary': '#d4d4d4',
      '--text-secondary': '#858585',
      '--text-muted': '#5a5a5a',
      '--border-color': '#3c3c3c',
      '--border-light': '#2d2d2d',
      '--accent-color': '#569cd6',
      '--accent-hover': '#6cb0e0',
      '--scrollbar-thumb': '#4a4a4a',
    },
  },
  {
    id: 'github-dark',
    name: 'Github Dark',
    type: 'dark',
    colors: {
      '--bg-primary': '#0d1117',
      '--bg-secondary': '#161b22',
      '--bg-sidebar': '#0d1117',
      '--bg-titlebar': '#161b22',
      '--bg-hover': '#1c2128',
      '--bg-active': '#262c36',
      '--text-primary': '#e6edf3',
      '--text-secondary': '#8b949e',
      '--text-muted': '#484f58',
      '--border-color': '#30363d',
      '--border-light': '#21262d',
      '--accent-color': '#58a6ff',
      '--accent-hover': '#79c0ff',
      '--scrollbar-thumb': '#484f58',
      '--hljs-keyword': '#ff7b72',
      '--hljs-string': '#a5d6ff',
      '--hljs-number': '#79c0ff',
      '--hljs-comment': '#8b949e',
      '--hljs-function': '#d2a8ff',
      '--hljs-variable': '#ffa657',
      '--hljs-type': '#79c0ff',
      '--hljs-built-in': '#ffa657',
      '--hljs-literal': '#79c0ff',
      '--hljs-title': '#d2a8ff',
      '--hljs-params': '#e6edf3',
      '--hljs-meta': '#8b949e',
      '--hljs-tag': '#7ee787',
      '--hljs-name': '#7ee787',
      '--hljs-attr': '#79c0ff',
      '--hljs-attribute': '#a5d6ff',
      '--hljs-selector': '#7ee787',
      '--hljs-property': '#79c0ff',
      '--hljs-punctuation': '#e6edf3',
      '--hljs-operator': '#ff7b72',
      '--hljs-regexp': '#a5d6ff',
      '--hljs-subst': '#ffa657',
      '--hljs-variable-constant': '#79c0ff',
      '--hljs-title-class-inherited': '#7ee787',
      '--hljs-selector-attr': '#d2a8ff',
      '--hljs-section': '#79c0ff',
      '--hljs-bullet': '#ffa657',
      '--hljs-link': '#58a6ff',
      '--hljs-quote': '#8b949e',
      '--hljs-code': '#ffa657',
      '--hljs-addition-color': '#7ee787',
      '--hljs-addition-bg': 'rgba(126, 231, 135, 0.1)',
      '--hljs-deletion-color': '#ffa198',
      '--hljs-deletion-bg': 'rgba(255, 161, 152, 0.1)',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    type: 'dark',
    colors: {
      '--bg-primary': '#282a36',
      '--bg-secondary': '#21222c',
      '--bg-sidebar': '#21222c',
      '--bg-titlebar': '#282a36',
      '--bg-hover': '#343746',
      '--bg-active': '#44475a',
      '--text-primary': '#f8f8f2',
      '--text-secondary': '#9da0b3',
      '--text-muted': '#6272a4',
      '--border-color': '#44475a',
      '--border-light': '#343746',
      '--accent-color': '#bd93f9',
      '--accent-hover': '#caa8fc',
      '--scrollbar-thumb': '#6272a4',
      '--hljs-keyword': '#ff79c6',
      '--hljs-string': '#f1fa8c',
      '--hljs-number': '#bd93f9',
      '--hljs-comment': '#6272a4',
      '--hljs-function': '#50fa7b',
      '--hljs-variable': '#f8f8f2',
      '--hljs-type': '#8be9fd',
      '--hljs-built-in': '#8be9fd',
      '--hljs-literal': '#bd93f9',
      '--hljs-title': '#50fa7b',
      '--hljs-params': '#ffb86c',
      '--hljs-meta': '#f8f8f2',
      '--hljs-tag': '#ff79c6',
      '--hljs-name': '#50fa7b',
      '--hljs-attr': '#8be9fd',
      '--hljs-attribute': '#f1fa8c',
      '--hljs-selector': '#50fa7b',
      '--hljs-property': '#8be9fd',
      '--hljs-punctuation': '#f8f8f2',
      '--hljs-operator': '#ff79c6',
      '--hljs-regexp': '#f1fa8c',
      '--hljs-subst': '#f8f8f2',
      '--hljs-variable-constant': '#bd93f9',
      '--hljs-title-class-inherited': '#50fa7b',
      '--hljs-selector-attr': '#8be9fd',
      '--hljs-section': '#bd93f9',
      '--hljs-bullet': '#8be9fd',
      '--hljs-link': '#8be9fd',
      '--hljs-quote': '#6272a4',
      '--hljs-code': '#ffb86c',
      '--hljs-addition-color': '#50fa7b',
      '--hljs-addition-bg': 'rgba(80, 250, 123, 0.1)',
      '--hljs-deletion-color': '#ff5555',
      '--hljs-deletion-bg': 'rgba(255, 85, 85, 0.1)',
    },
  },
  {
    id: 'one-dark',
    name: 'One Dark',
    type: 'dark',
    colors: {
      '--bg-primary': '#282c34',
      '--bg-secondary': '#21252b',
      '--bg-sidebar': '#21252b',
      '--bg-titlebar': '#282c34',
      '--bg-hover': '#2c313a',
      '--bg-active': '#3a3f4b',
      '--text-primary': '#abb2bf',
      '--text-secondary': '#7f848e',
      '--text-muted': '#5c6370',
      '--border-color': '#3e4451',
      '--border-light': '#2c313a',
      '--accent-color': '#61afef',
      '--accent-hover': '#82c4f8',
      '--scrollbar-thumb': '#4b5263',
      '--hljs-keyword': '#c678dd',
      '--hljs-string': '#98c379',
      '--hljs-number': '#d19a66',
      '--hljs-comment': '#5c6370',
      '--hljs-function': '#61afef',
      '--hljs-variable': '#e06c75',
      '--hljs-type': '#e5c07b',
      '--hljs-built-in': '#e5c07b',
      '--hljs-literal': '#d19a66',
      '--hljs-title': '#61afef',
      '--hljs-params': '#abb2bf',
      '--hljs-meta': '#abb2bf',
      '--hljs-tag': '#e06c75',
      '--hljs-name': '#e06c75',
      '--hljs-attr': '#d19a66',
      '--hljs-attribute': '#98c379',
      '--hljs-selector': '#e06c75',
      '--hljs-property': '#e06c75',
      '--hljs-punctuation': '#abb2bf',
      '--hljs-operator': '#56b6c2',
      '--hljs-regexp': '#98c379',
      '--hljs-subst': '#e06c75',
      '--hljs-variable-constant': '#d19a66',
      '--hljs-title-class-inherited': '#e5c07b',
      '--hljs-selector-attr': '#d19a66',
      '--hljs-section': '#e06c75',
      '--hljs-bullet': '#e06c75',
      '--hljs-link': '#61afef',
      '--hljs-quote': '#5c6370',
      '--hljs-code': '#98c379',
      '--hljs-addition-color': '#98c379',
      '--hljs-addition-bg': 'rgba(152, 195, 121, 0.1)',
      '--hljs-deletion-color': '#e06c75',
      '--hljs-deletion-bg': 'rgba(224, 108, 117, 0.1)',
    },
  },
];

export function getThemeById(id: string): ColorTheme | undefined {
  return builtinThemes.find(t => t.id === id);
}

export function getLightThemes(): ColorTheme[] {
  return builtinThemes.filter(t => t.type === 'light');
}

export function getDarkThemes(): ColorTheme[] {
  return builtinThemes.filter(t => t.type === 'dark');
}
