/**
 * Thin shell over `@moraya/core/i18n` — the unified i18n engine introduced
 * in v0.96.0. This file used to own its own implementation + 12 locale
 * JSONs; the engine and the locales now live in moraya-core.
 *
 * Public surface preserved for the 1,716 existing PC callsites:
 *   - `t` stays a Svelte derived store so `$t('foo')` template usage
 *     keeps auto re-rendering on locale switch.
 *   - `setLocale` stays sync-callable (eager preload at module load means
 *     the bundle is already cached when the consumer calls it).
 *   - `resolveForLocale` / `resolveAllLocales` stay sync — same reason.
 *   - `detectSystemLocale`, `isRTL` re-exported verbatim.
 *
 * Persistence: lives in `src/lib/stores/settings-store.ts` via Tauri
 * plugin-store. This shell doesn't touch persistence; the settings-store
 * calls `setLocale(...)` itself after restoring its state from disk.
 */

import {
  t as coreT,
  setLocale as coreSetLocale,
  locale as coreLocale,
  preloadAllLocales,
  detectSystemLocale,
  isRTL,
  resolveForLocale,
  resolveAllLocales,
  type SupportedLocale,
} from '@moraya/core/i18n'
import { derived } from 'svelte/store'

// Eager-load all 12 bundles at module load — restores the PC-era assumption
// that every locale's strings are sync-available (the prior implementation
// statically imported all 12 JSONs at the top of the file). This Promise
// resolves quickly (~12 dynamic imports running in parallel via the
// bundler's chunk loader) and is awaited inside loader.ts's memoized cache.
void preloadAllLocales()

/**
 * App-local i18n overrides. moraya consumes the *published* `@moraya/core` for
 * its 12-locale message set, so a brand-new UI string would otherwise need a
 * core release. This map adds app-only keys here — fully localized across all
 * 12 locales — to be folded into core on its next release. `t` checks this map
 * first, then falls back to core.
 */
const LOCAL_OVERRIDES: Partial<Record<SupportedLocale, Record<string, string>>> = {
  'en':      { 'menu.terms_of_service': 'Terms of Service', 'math.placeholder': 'Enter LaTeX, e.g. x_0 or \\frac{a}{b}', 'mcp.lan.only_stdio': 'Only stdio servers can be exposed over LAN. http/sse servers already have a network URL.', 'menu.undo': 'Undo', 'menu.redo': 'Redo', 'menu.select_all': 'Select All', 'mcp.lan.expose': 'Expose over LAN', 'mcp.lan.config': 'Config', 'mcp.lan.copy': 'Copy', 'mcp.lan.copy_config': 'Copy config', 'mcp.lan.hint': 'Same Wi-Fi only. Sent in plaintext over the LAN, secured by the token. macOS may ask to allow incoming connections.', 'mcp.lan.scan_hint': 'Scan with the Moraya mobile app', 'kb_sync.conflict.take_local': 'Local', 'kb_sync.conflict.take_remote': 'Remote', 'kb_sync.conflict.take_both': 'Both', 'kb_sync.conflict.merge_preview': 'Merge preview', 'kb_sync.conflict.unresolved': '{n} unresolved', 'kb_sync.conflict.apply_upload': 'Apply & upload', 'prompt_asset.title': 'Prompt Assets', 'prompt_asset.desc': 'Recover the prompts you sent to Claude Code and save them as Markdown assets in a knowledge base.', 'prompt_asset.no_kb': 'Create or open a knowledge base first.', 'prompt_asset.target_kb': 'Save to', 'prompt_asset.claude_dir': 'Claude Code directory', 'prompt_asset.privacy_note': 'Transcripts are read locally and only the prompts you select are written. Nothing is uploaded until you sync the knowledge base.', 'prompt_asset.scan_btn': 'Scan', 'prompt_asset.scanning': 'Scanning…', 'prompt_asset.scan_empty': 'No new prompts found.', 'prompt_asset.scan_error': 'Scan failed: {error}', 'prompt_asset.preview_title': 'Prompts found', 'prompt_asset.selected_count': '{n} selected', 'prompt_asset.import_btn': 'Import {n}', 'prompt_asset.importing': 'Importing…', 'prompt_asset.import_done': 'Imported {count} prompts.', 'prompt_asset.import_error': 'Import failed: {error}' },
  'zh-CN':   { 'menu.terms_of_service': '服务条款', 'math.placeholder': '输入 LaTeX，例如 x_0 或 \\frac{a}{b}', 'mcp.lan.only_stdio': '仅 stdio 类型的服务可暴露到局域网。http/sse 服务本身已有网络地址，无需桥接。', 'menu.undo': '撤销', 'menu.redo': '重做', 'menu.select_all': '全选', 'mcp.lan.expose': '暴露到局域网', 'mcp.lan.config': '配置', 'mcp.lan.copy': '复制', 'mcp.lan.copy_config': '复制配置', 'mcp.lan.hint': '需同一 Wi-Fi。局域网内明文传输、由 token 保护；macOS 可能弹窗请求允许传入连接。', 'mcp.lan.scan_hint': '用 Moraya 手机端扫码接入', 'kb_sync.conflict.take_local': '本地', 'kb_sync.conflict.take_remote': '云端', 'kb_sync.conflict.take_both': '两者', 'kb_sync.conflict.merge_preview': '合并预览', 'kb_sync.conflict.unresolved': '{n} 处未解决', 'kb_sync.conflict.apply_upload': '应用并上传', 'prompt_asset.title': '提示词资产', 'prompt_asset.desc': '把你发给 Claude Code 的提示词找回来，保存为知识库里的 Markdown 资产。', 'prompt_asset.no_kb': '请先创建或打开一个知识库。', 'prompt_asset.target_kb': '保存到', 'prompt_asset.claude_dir': 'Claude Code 目录', 'prompt_asset.privacy_note': '转录在本地读取，仅写入你勾选的提示词。同步知识库前不会上传任何内容。', 'prompt_asset.scan_btn': '扫描', 'prompt_asset.scanning': '扫描中…', 'prompt_asset.scan_empty': '未发现新的提示词。', 'prompt_asset.scan_error': '扫描失败：{error}', 'prompt_asset.preview_title': '发现的提示词', 'prompt_asset.selected_count': '已选 {n} 条', 'prompt_asset.import_btn': '导入 {n} 条', 'prompt_asset.importing': '导入中…', 'prompt_asset.import_done': '已导入 {count} 条提示词。', 'prompt_asset.import_error': '导入失败：{error}' },
  'zh-Hant': { 'menu.terms_of_service': '服務條款', 'math.placeholder': '輸入 LaTeX，例如 x_0 或 \\frac{a}{b}', 'mcp.lan.only_stdio': '僅 stdio 類型的服務可暴露到區域網路。http/sse 服務本身已有網路位址，無需橋接。', 'menu.undo': '復原', 'menu.redo': '重做', 'menu.select_all': '全選', 'mcp.lan.expose': '暴露到區域網路', 'mcp.lan.config': '設定', 'mcp.lan.copy': '複製', 'mcp.lan.copy_config': '複製設定', 'mcp.lan.hint': '需同一 Wi-Fi。區域網路內明文傳輸、由 token 保護；macOS 可能彈窗請求允許傳入連線。', 'mcp.lan.scan_hint': '用 Moraya 手機端掃碼接入', 'kb_sync.conflict.take_local': '本地', 'kb_sync.conflict.take_remote': '雲端', 'kb_sync.conflict.take_both': '兩者', 'kb_sync.conflict.merge_preview': '合併預覽', 'kb_sync.conflict.unresolved': '{n} 處未解決', 'kb_sync.conflict.apply_upload': '套用並上傳', 'prompt_asset.title': '提示詞資產', 'prompt_asset.desc': '把你傳給 Claude Code 的提示詞找回來，儲存為知識庫裡的 Markdown 資產。', 'prompt_asset.no_kb': '請先建立或開啟一個知識庫。', 'prompt_asset.target_kb': '儲存到', 'prompt_asset.claude_dir': 'Claude Code 目錄', 'prompt_asset.privacy_note': '轉錄在本機讀取，僅寫入你勾選的提示詞。同步知識庫前不會上傳任何內容。', 'prompt_asset.scan_btn': '掃描', 'prompt_asset.scanning': '掃描中…', 'prompt_asset.scan_empty': '未發現新的提示詞。', 'prompt_asset.scan_error': '掃描失敗：{error}', 'prompt_asset.preview_title': '發現的提示詞', 'prompt_asset.selected_count': '已選 {n} 條', 'prompt_asset.import_btn': '匯入 {n} 條', 'prompt_asset.importing': '匯入中…', 'prompt_asset.import_done': '已匯入 {count} 條提示詞。', 'prompt_asset.import_error': '匯入失敗：{error}' },
  'ar':      { 'menu.terms_of_service': 'شروط الخدمة', 'math.placeholder': 'أدخل LaTeX، مثل x_0 أو \\frac{a}{b}', 'mcp.lan.only_stdio': 'يمكن كشف خوادم stdio فقط عبر الشبكة المحلية. خوادم http/sse لديها بالفعل عنوان شبكة.', 'menu.undo': 'تراجع', 'menu.redo': 'إعادة', 'menu.select_all': 'تحديد الكل', 'mcp.lan.expose': 'الكشف عبر الشبكة المحلية', 'mcp.lan.config': 'الإعداد', 'mcp.lan.copy': 'نسخ', 'mcp.lan.copy_config': 'نسخ الإعداد', 'mcp.lan.hint': 'نفس شبكة Wi-Fi فقط. يُرسل كنص عادي عبر الشبكة المحلية، محميًا بالرمز.', 'mcp.lan.scan_hint': 'امسح باستخدام تطبيق Moraya', 'kb_sync.conflict.take_local': 'محلي', 'kb_sync.conflict.take_remote': 'سحابي', 'kb_sync.conflict.take_both': 'كلاهما', 'kb_sync.conflict.merge_preview': 'معاينة الدمج', 'kb_sync.conflict.unresolved': '{n} غير محلولة', 'kb_sync.conflict.apply_upload': 'تطبيق ورفع', 'prompt_asset.title': 'أصول التوجيهات', 'prompt_asset.desc': 'استعد التوجيهات التي أرسلتها إلى Claude Code واحفظها كأصول Markdown في قاعدة معرفة.', 'prompt_asset.no_kb': 'أنشئ أو افتح قاعدة معرفة أولاً.', 'prompt_asset.target_kb': 'حفظ إلى', 'prompt_asset.claude_dir': 'مجلد Claude Code', 'prompt_asset.privacy_note': 'تُقرأ النصوص محليًا ولا يُكتب سوى التوجيهات التي تحددها. لا يُرفع شيء حتى تُزامن قاعدة المعرفة.', 'prompt_asset.scan_btn': 'فحص', 'prompt_asset.scanning': 'جارٍ الفحص…', 'prompt_asset.scan_empty': 'لم يُعثر على توجيهات جديدة.', 'prompt_asset.scan_error': 'فشل الفحص: {error}', 'prompt_asset.preview_title': 'التوجيهات المكتشفة', 'prompt_asset.selected_count': 'محدد {n}', 'prompt_asset.import_btn': 'استيراد {n}', 'prompt_asset.importing': 'جارٍ الاستيراد…', 'prompt_asset.import_done': 'تم استيراد {count} توجيهًا.', 'prompt_asset.import_error': 'فشل الاستيراد: {error}' },
  'de':      { 'menu.terms_of_service': 'Nutzungsbedingungen', 'math.placeholder': 'LaTeX eingeben, z. B. x_0 oder \\frac{a}{b}', 'mcp.lan.only_stdio': 'Nur stdio-Server können im LAN freigegeben werden. http/sse-Server haben bereits eine Netzwerk-URL.', 'menu.undo': 'Rückgängig', 'menu.redo': 'Wiederholen', 'menu.select_all': 'Alles auswählen', 'mcp.lan.expose': 'Im LAN freigeben', 'mcp.lan.config': 'Konfig', 'mcp.lan.copy': 'Kopieren', 'mcp.lan.copy_config': 'Konfig kopieren', 'mcp.lan.hint': 'Nur gleiches WLAN. Im Klartext über das LAN, durch das Token gesichert. macOS fragt ggf. nach eingehenden Verbindungen.', 'mcp.lan.scan_hint': 'Mit der Moraya-App scannen', 'kb_sync.conflict.take_local': 'Lokal', 'kb_sync.conflict.take_remote': 'Cloud', 'kb_sync.conflict.take_both': 'Beide', 'kb_sync.conflict.merge_preview': 'Zusammenführungs-Vorschau', 'kb_sync.conflict.unresolved': '{n} ungelöst', 'kb_sync.conflict.apply_upload': 'Anwenden & hochladen', 'prompt_asset.title': 'Prompt-Assets', 'prompt_asset.desc': 'Hol die an Claude Code gesendeten Prompts zurück und speichere sie als Markdown-Assets in einer Wissensdatenbank.', 'prompt_asset.no_kb': 'Erstelle oder öffne zuerst eine Wissensdatenbank.', 'prompt_asset.target_kb': 'Speichern in', 'prompt_asset.claude_dir': 'Claude-Code-Verzeichnis', 'prompt_asset.privacy_note': 'Transkripte werden lokal gelesen; nur ausgewählte Prompts werden geschrieben. Nichts wird hochgeladen, bis du die Wissensdatenbank synchronisierst.', 'prompt_asset.scan_btn': 'Scannen', 'prompt_asset.scanning': 'Scannen…', 'prompt_asset.scan_empty': 'Keine neuen Prompts gefunden.', 'prompt_asset.scan_error': 'Scan fehlgeschlagen: {error}', 'prompt_asset.preview_title': 'Gefundene Prompts', 'prompt_asset.selected_count': '{n} ausgewählt', 'prompt_asset.import_btn': '{n} importieren', 'prompt_asset.importing': 'Import…', 'prompt_asset.import_done': '{count} Prompts importiert.', 'prompt_asset.import_error': 'Import fehlgeschlagen: {error}' },
  'es':      { 'menu.terms_of_service': 'Términos de servicio', 'math.placeholder': 'Introduce LaTeX, p. ej. x_0 o \\frac{a}{b}', 'mcp.lan.only_stdio': 'Solo los servidores stdio pueden exponerse en la LAN. Los servidores http/sse ya tienen una URL de red.', 'menu.undo': 'Deshacer', 'menu.redo': 'Rehacer', 'menu.select_all': 'Seleccionar todo', 'mcp.lan.expose': 'Exponer en la LAN', 'mcp.lan.config': 'Configuración', 'mcp.lan.copy': 'Copiar', 'mcp.lan.copy_config': 'Copiar configuración', 'mcp.lan.hint': 'Solo la misma Wi-Fi. En texto plano por la LAN, protegido por el token. macOS puede pedir permitir conexiones entrantes.', 'mcp.lan.scan_hint': 'Escanea con la app de Moraya', 'kb_sync.conflict.take_local': 'Local', 'kb_sync.conflict.take_remote': 'Nube', 'kb_sync.conflict.take_both': 'Ambos', 'kb_sync.conflict.merge_preview': 'Vista previa de fusión', 'kb_sync.conflict.unresolved': '{n} sin resolver', 'kb_sync.conflict.apply_upload': 'Aplicar y subir', 'prompt_asset.title': 'Activos de prompts', 'prompt_asset.desc': 'Recupera los prompts que enviaste a Claude Code y guárdalos como activos Markdown en una base de conocimiento.', 'prompt_asset.no_kb': 'Crea o abre primero una base de conocimiento.', 'prompt_asset.target_kb': 'Guardar en', 'prompt_asset.claude_dir': 'Directorio de Claude Code', 'prompt_asset.privacy_note': 'Las transcripciones se leen localmente y solo se escriben los prompts que selecciones. No se sube nada hasta que sincronices la base de conocimiento.', 'prompt_asset.scan_btn': 'Escanear', 'prompt_asset.scanning': 'Escaneando…', 'prompt_asset.scan_empty': 'No se encontraron prompts nuevos.', 'prompt_asset.scan_error': 'Error al escanear: {error}', 'prompt_asset.preview_title': 'Prompts encontrados', 'prompt_asset.selected_count': '{n} seleccionados', 'prompt_asset.import_btn': 'Importar {n}', 'prompt_asset.importing': 'Importando…', 'prompt_asset.import_done': 'Se importaron {count} prompts.', 'prompt_asset.import_error': 'Error al importar: {error}' },
  'fr':      { 'menu.terms_of_service': 'Conditions d\'utilisation', 'math.placeholder': 'Saisir du LaTeX, p. ex. x_0 ou \\frac{a}{b}', 'mcp.lan.only_stdio': 'Seuls les serveurs stdio peuvent être exposés sur le réseau local. Les serveurs http/sse ont déjà une URL réseau.', 'menu.undo': 'Annuler', 'menu.redo': 'Rétablir', 'menu.select_all': 'Tout sélectionner', 'mcp.lan.expose': 'Exposer sur le réseau local', 'mcp.lan.config': 'Config', 'mcp.lan.copy': 'Copier', 'mcp.lan.copy_config': 'Copier la config', 'mcp.lan.hint': 'Même Wi-Fi uniquement. En clair sur le réseau local, protégé par le jeton. macOS peut demander d’autoriser les connexions entrantes.', 'mcp.lan.scan_hint': 'Scannez avec l’app Moraya', 'kb_sync.conflict.take_local': 'Local', 'kb_sync.conflict.take_remote': 'Cloud', 'kb_sync.conflict.take_both': 'Les deux', 'kb_sync.conflict.merge_preview': 'Aperçu de la fusion', 'kb_sync.conflict.unresolved': '{n} non résolus', 'kb_sync.conflict.apply_upload': 'Appliquer et envoyer', 'prompt_asset.title': 'Ressources de prompts', 'prompt_asset.desc': 'Récupérez les prompts envoyés à Claude Code et enregistrez-les comme ressources Markdown dans une base de connaissances.', 'prompt_asset.no_kb': 'Créez ou ouvrez d’abord une base de connaissances.', 'prompt_asset.target_kb': 'Enregistrer dans', 'prompt_asset.claude_dir': 'Répertoire Claude Code', 'prompt_asset.privacy_note': 'Les transcriptions sont lues localement et seuls les prompts sélectionnés sont écrits. Rien n’est envoyé tant que vous ne synchronisez pas la base de connaissances.', 'prompt_asset.scan_btn': 'Analyser', 'prompt_asset.scanning': 'Analyse…', 'prompt_asset.scan_empty': 'Aucun nouveau prompt trouvé.', 'prompt_asset.scan_error': 'Échec de l’analyse : {error}', 'prompt_asset.preview_title': 'Prompts trouvés', 'prompt_asset.selected_count': '{n} sélectionnés', 'prompt_asset.import_btn': 'Importer {n}', 'prompt_asset.importing': 'Importation…', 'prompt_asset.import_done': '{count} prompts importés.', 'prompt_asset.import_error': 'Échec de l’importation : {error}' },
  'hi':      { 'menu.terms_of_service': 'सेवा की शर्तें', 'math.placeholder': 'LaTeX दर्ज करें, जैसे x_0 या \\frac{a}{b}', 'mcp.lan.only_stdio': 'केवल stdio सर्वर को LAN पर उपलब्ध कराया जा सकता है। http/sse सर्वर के पास पहले से नेटवर्क URL है।', 'menu.undo': 'पूर्ववत् करें', 'menu.redo': 'फिर से करें', 'menu.select_all': 'सभी चुनें', 'mcp.lan.expose': 'LAN पर उपलब्ध कराएं', 'mcp.lan.config': 'कॉन्फ़िग', 'mcp.lan.copy': 'कॉपी', 'mcp.lan.copy_config': 'कॉन्फ़िग कॉपी करें', 'mcp.lan.hint': 'केवल समान Wi-Fi। LAN पर सादे रूप में भेजा जाता है, टोकन से सुरक्षित।', 'mcp.lan.scan_hint': 'Moraya मोबाइल ऐप से स्कैन करें', 'kb_sync.conflict.take_local': 'स्थानीय', 'kb_sync.conflict.take_remote': 'क्लाउड', 'kb_sync.conflict.take_both': 'दोनों', 'kb_sync.conflict.merge_preview': 'मर्ज पूर्वावलोकन', 'kb_sync.conflict.unresolved': '{n} अनसुलझे', 'kb_sync.conflict.apply_upload': 'लागू करें और अपलोड करें', 'prompt_asset.title': 'प्रॉम्प्ट एसेट', 'prompt_asset.desc': 'Claude Code को भेजे गए अपने प्रॉम्प्ट पुनः प्राप्त करें और उन्हें ज्ञानकोश में Markdown एसेट के रूप में सहेजें।', 'prompt_asset.no_kb': 'पहले एक ज्ञानकोश बनाएं या खोलें।', 'prompt_asset.target_kb': 'यहाँ सहेजें', 'prompt_asset.claude_dir': 'Claude Code निर्देशिका', 'prompt_asset.privacy_note': 'ट्रांसक्रिप्ट स्थानीय रूप से पढ़े जाते हैं और केवल चयनित प्रॉम्प्ट लिखे जाते हैं। ज्ञानकोश सिंक करने तक कुछ भी अपलोड नहीं होता।', 'prompt_asset.scan_btn': 'स्कैन', 'prompt_asset.scanning': 'स्कैन हो रहा है…', 'prompt_asset.scan_empty': 'कोई नया प्रॉम्प्ट नहीं मिला।', 'prompt_asset.scan_error': 'स्कैन विफल: {error}', 'prompt_asset.preview_title': 'मिले प्रॉम्प्ट', 'prompt_asset.selected_count': '{n} चयनित', 'prompt_asset.import_btn': '{n} आयात करें', 'prompt_asset.importing': 'आयात हो रहा है…', 'prompt_asset.import_done': '{count} प्रॉम्प्ट आयात किए गए।', 'prompt_asset.import_error': 'आयात विफल: {error}' },
  'ja':      { 'menu.terms_of_service': '利用規約', 'math.placeholder': 'LaTeX を入力（例：x_0、\\frac{a}{b}）', 'mcp.lan.only_stdio': 'LAN に公開できるのは stdio サーバーのみです。http/sse サーバーには既にネットワーク URL があります。', 'menu.undo': '取り消す', 'menu.redo': 'やり直す', 'menu.select_all': 'すべて選択', 'mcp.lan.expose': 'LAN に公開', 'mcp.lan.config': '設定', 'mcp.lan.copy': 'コピー', 'mcp.lan.copy_config': '設定をコピー', 'mcp.lan.hint': '同一 Wi-Fi のみ。LAN 上は平文で送信され、トークンで保護されます。macOS が着信接続の許可を求める場合があります。', 'mcp.lan.scan_hint': 'Moraya モバイルでスキャン', 'kb_sync.conflict.take_local': 'ローカル', 'kb_sync.conflict.take_remote': 'クラウド', 'kb_sync.conflict.take_both': '両方', 'kb_sync.conflict.merge_preview': 'マージプレビュー', 'kb_sync.conflict.unresolved': '{n} 件未解決', 'kb_sync.conflict.apply_upload': '適用してアップロード', 'prompt_asset.title': 'プロンプト資産', 'prompt_asset.desc': 'Claude Code に送ったプロンプトを回収し、ナレッジベースに Markdown 資産として保存します。', 'prompt_asset.no_kb': '先にナレッジベースを作成または開いてください。', 'prompt_asset.target_kb': '保存先', 'prompt_asset.claude_dir': 'Claude Code のディレクトリ', 'prompt_asset.privacy_note': 'トランスクリプトはローカルで読み取られ、選択したプロンプトのみ書き込まれます。ナレッジベースを同期するまで何もアップロードされません。', 'prompt_asset.scan_btn': 'スキャン', 'prompt_asset.scanning': 'スキャン中…', 'prompt_asset.scan_empty': '新しいプロンプトは見つかりませんでした。', 'prompt_asset.scan_error': 'スキャンに失敗しました: {error}', 'prompt_asset.preview_title': '見つかったプロンプト', 'prompt_asset.selected_count': '{n} 件選択', 'prompt_asset.import_btn': '{n} 件をインポート', 'prompt_asset.importing': 'インポート中…', 'prompt_asset.import_done': '{count} 件のプロンプトをインポートしました。', 'prompt_asset.import_error': 'インポートに失敗しました: {error}' },
  'ko':      { 'menu.terms_of_service': '서비스 이용약관', 'math.placeholder': 'LaTeX 입력 (예: x_0, \\frac{a}{b})', 'mcp.lan.only_stdio': 'stdio 서버만 LAN에 노출할 수 있습니다. http/sse 서버에는 이미 네트워크 URL이 있습니다.', 'menu.undo': '실행 취소', 'menu.redo': '다시 실행', 'menu.select_all': '모두 선택', 'mcp.lan.expose': 'LAN에 노출', 'mcp.lan.config': '구성', 'mcp.lan.copy': '복사', 'mcp.lan.copy_config': '구성 복사', 'mcp.lan.hint': '동일 Wi-Fi만 가능. LAN에서 평문으로 전송되며 토큰으로 보호됩니다.', 'mcp.lan.scan_hint': 'Moraya 모바일 앱으로 스캔', 'kb_sync.conflict.take_local': '로컬', 'kb_sync.conflict.take_remote': '클라우드', 'kb_sync.conflict.take_both': '둘 다', 'kb_sync.conflict.merge_preview': '병합 미리보기', 'kb_sync.conflict.unresolved': '{n}개 미해결', 'kb_sync.conflict.apply_upload': '적용 및 업로드', 'prompt_asset.title': '프롬프트 자산', 'prompt_asset.desc': 'Claude Code에 보낸 프롬프트를 되찾아 지식 베이스에 Markdown 자산으로 저장합니다.', 'prompt_asset.no_kb': '먼저 지식 베이스를 만들거나 여세요.', 'prompt_asset.target_kb': '저장 위치', 'prompt_asset.claude_dir': 'Claude Code 디렉터리', 'prompt_asset.privacy_note': '전사는 로컬에서 읽으며 선택한 프롬프트만 기록됩니다. 지식 베이스를 동기화하기 전에는 아무것도 업로드되지 않습니다.', 'prompt_asset.scan_btn': '스캔', 'prompt_asset.scanning': '스캔 중…', 'prompt_asset.scan_empty': '새 프롬프트가 없습니다.', 'prompt_asset.scan_error': '스캔 실패: {error}', 'prompt_asset.preview_title': '찾은 프롬프트', 'prompt_asset.selected_count': '{n}개 선택됨', 'prompt_asset.import_btn': '{n}개 가져오기', 'prompt_asset.importing': '가져오는 중…', 'prompt_asset.import_done': '{count}개의 프롬프트를 가져왔습니다.', 'prompt_asset.import_error': '가져오기 실패: {error}' },
  'pt':      { 'menu.terms_of_service': 'Termos de Serviço', 'math.placeholder': 'Digite LaTeX, ex.: x_0 ou \\frac{a}{b}', 'mcp.lan.only_stdio': 'Apenas servidores stdio podem ser expostos na LAN. Servidores http/sse já têm uma URL de rede.', 'menu.undo': 'Desfazer', 'menu.redo': 'Refazer', 'menu.select_all': 'Selecionar tudo', 'mcp.lan.expose': 'Expor na LAN', 'mcp.lan.config': 'Config', 'mcp.lan.copy': 'Copiar', 'mcp.lan.copy_config': 'Copiar config', 'mcp.lan.hint': 'Apenas o mesmo Wi-Fi. Em texto puro na LAN, protegido pelo token. O macOS pode pedir para permitir conexões.', 'mcp.lan.scan_hint': 'Escaneie com o app Moraya', 'kb_sync.conflict.take_local': 'Local', 'kb_sync.conflict.take_remote': 'Nuvem', 'kb_sync.conflict.take_both': 'Ambos', 'kb_sync.conflict.merge_preview': 'Pré-visualização da mesclagem', 'kb_sync.conflict.unresolved': '{n} não resolvidos', 'kb_sync.conflict.apply_upload': 'Aplicar e enviar', 'prompt_asset.title': 'Ativos de prompts', 'prompt_asset.desc': 'Recupere os prompts que você enviou ao Claude Code e salve-os como ativos Markdown em uma base de conhecimento.', 'prompt_asset.no_kb': 'Crie ou abra uma base de conhecimento primeiro.', 'prompt_asset.target_kb': 'Salvar em', 'prompt_asset.claude_dir': 'Diretório do Claude Code', 'prompt_asset.privacy_note': 'As transcrições são lidas localmente e apenas os prompts selecionados são gravados. Nada é enviado até você sincronizar a base de conhecimento.', 'prompt_asset.scan_btn': 'Verificar', 'prompt_asset.scanning': 'Verificando…', 'prompt_asset.scan_empty': 'Nenhum prompt novo encontrado.', 'prompt_asset.scan_error': 'Falha na verificação: {error}', 'prompt_asset.preview_title': 'Prompts encontrados', 'prompt_asset.selected_count': '{n} selecionados', 'prompt_asset.import_btn': 'Importar {n}', 'prompt_asset.importing': 'Importando…', 'prompt_asset.import_done': '{count} prompts importados.', 'prompt_asset.import_error': 'Falha na importação: {error}' },
  'ru':      { 'menu.terms_of_service': 'Условия обслуживания', 'math.placeholder': 'Введите LaTeX, напр. x_0 или \\frac{a}{b}', 'mcp.lan.only_stdio': 'В локальной сети можно открыть только stdio-серверы. У http/sse-серверов уже есть сетевой URL.', 'menu.undo': 'Отменить', 'menu.redo': 'Повторить', 'menu.select_all': 'Выделить всё', 'mcp.lan.expose': 'Открыть в локальной сети', 'mcp.lan.config': 'Конфиг', 'mcp.lan.copy': 'Копировать', 'mcp.lan.copy_config': 'Копировать конфиг', 'mcp.lan.hint': 'Только та же Wi-Fi. Передаётся открытым текстом по локальной сети, защищено токеном.', 'mcp.lan.scan_hint': 'Сканируйте в приложении Moraya', 'kb_sync.conflict.take_local': 'Локально', 'kb_sync.conflict.take_remote': 'Облако', 'kb_sync.conflict.take_both': 'Оба', 'kb_sync.conflict.merge_preview': 'Предпросмотр слияния', 'kb_sync.conflict.unresolved': '{n} не разрешено', 'kb_sync.conflict.apply_upload': 'Применить и загрузить', 'prompt_asset.title': 'Активы промптов', 'prompt_asset.desc': 'Верните промпты, отправленные в Claude Code, и сохраните их как Markdown-активы в базе знаний.', 'prompt_asset.no_kb': 'Сначала создайте или откройте базу знаний.', 'prompt_asset.target_kb': 'Сохранить в', 'prompt_asset.claude_dir': 'Каталог Claude Code', 'prompt_asset.privacy_note': 'Транскрипты читаются локально, записываются только выбранные промпты. Ничего не загружается, пока вы не синхронизируете базу знаний.', 'prompt_asset.scan_btn': 'Сканировать', 'prompt_asset.scanning': 'Сканирование…', 'prompt_asset.scan_empty': 'Новых промптов не найдено.', 'prompt_asset.scan_error': 'Ошибка сканирования: {error}', 'prompt_asset.preview_title': 'Найденные промпты', 'prompt_asset.selected_count': 'Выбрано: {n}', 'prompt_asset.import_btn': 'Импортировать {n}', 'prompt_asset.importing': 'Импорт…', 'prompt_asset.import_done': 'Импортировано промптов: {count}.', 'prompt_asset.import_error': 'Ошибка импорта: {error}' },
}

/**
 * Svelte derived store. `$t('foo')` in templates re-evaluates whenever the
 * locale store updates, so component re-renders are automatic. App-local
 * overrides resolve first, then core.
 */
export const t = derived(coreLocale, ($loc) => {
  return (...args: Parameters<typeof coreT>): string => {
    const [key, params] = args
    const override = LOCAL_OVERRIDES[$loc]?.[key] ?? LOCAL_OVERRIDES['en']?.[key]
    if (override !== undefined) {
      if (!params) return override
      return Object.entries(params).reduce(
        (acc, [k, v]) => acc.replaceAll(`{${k}}`, String(v)),
        override,
      )
    }
    return coreT(...args)
  }
})

/** Re-exported locale store for `import { locale } from '$lib/i18n'`. */
export const locale = coreLocale

/**
 * Sync-callable setLocale. Returns void (the prior signature). The async
 * load inside coreSetLocale resolves immediately after the eager preload
 * above finishes, and re-resolves are cache hits.
 */
export function setLocale(loc: SupportedLocale): void {
  void coreSetLocale(loc)
}

export { detectSystemLocale, isRTL, resolveForLocale, resolveAllLocales }
